name: Autofix — Sync & Build

on:
  # تشغيل يدوي من واجهة GitHub Actions (زر Run workflow)
  workflow_dispatch:
    inputs:
      mode:
        description: 'What to run'
        type: choice
        default: quick
        options: [quick, full]
  # تشغيل مجدول (اختياري)
  schedule:
    - cron: '0 3 * * *'   # يوميّاً 03:00 UTC

permissions:
  contents: write          # نحتاج ندفش تغييرات/فروع
  pull-requests: write     # لفتح PR تلقائي
  actions: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show context
        run: |
          echo "Actor: $GITHUB_ACTOR"
          echo "Repo:  $GITHUB_REPOSITORY"
          echo "Ref:   $GITHUB_REF"
          echo "Mode:  ${{ inputs.mode }}"

      # سكربت اختياري: اذا عندك سكربت يصلّح/يحدّث ملفات، ضعه في scripts/autofix.sh
      - name: Run local autofix script (if exists)
        shell: bash
        run: |
          if [ -x scripts/autofix.sh ]; then
            echo "Running scripts/autofix.sh …"
            scripts/autofix.sh "${{ inputs.mode }}"
          else
            echo "No scripts/autofix.sh found — skipping."
          fi

      # اذا ما في تغييرات رح يطلع step التالي No changes
      - name: Create PR with changes (if any)
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ci/autofix
          commit-message: 'chore(autofix): apply automated fixes'
          title: 'chore(autofix): apply automated fixes'
          body: |
            Automated fixes by **Autofix — Sync & Build**.
            Trigger: ${{ github.event_name }} — Mode: `${{ inputs.mode }}`
          labels: |
            ci
            autopilot
          draft: false
