name: Manos Agent – Pull & Execute Ops

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run_agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm i --no-audit --no-fund

      - name: Run manos-agent (long-poll once)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          VA_BASE: ${{ secrets.VA_BASE }}
          MANOS_TOKEN: ${{ secrets.MANOS_TOKEN }}
          MANUS_API_URL: ${{ secrets.MANUS_API_URL }}
          MANOS_API_KEY: ${{ secrets.MANOS_API_KEY }}
        run: |
          node manos-agent.mjs
